import dotenv from "dotenv";

dotenv.config();

export const {
  PORT,
  MONGODB_ATLAS_URL,
  NODEMAILER_USER_EMAIL,
  NODEMAILER_USER_PASSWORD,
  OTP_LENGTH,
  OTP_EXPIRES_SECONDS,
  OTP_MAX_ATTEMPTS,
  HASH_OTP,
  BCRYPT_SALT_ROUNDS,
  JWT_ACCESS_TOKEN_SECRET_KEY,
  JWT_REFRESH_TOKEN_SECRET_KEY,
  JWT_ACCESS_TOKEN_EXPIRES_IN,
  JWT_REFRESH_TOKEN_EXPIRES_IN,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  NODE_ENV,
} = process.env;
